# Generated by Django 5.1.1 on 2024-10-01 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(default='', max_length=50)),
                ('away', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('tip', models.CharField(blank=True, default='', max_length=40)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('odd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('results', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProofs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='LastWeekGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(default='', max_length=50)),
                ('away', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('odd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tip', models.CharField(blank=True, default='', max_length=40)),
                ('results', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('message', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NextGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(default='', max_length=50)),
                ('away', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('odd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('results', models.TextField(blank=True)),
            ],
        ),
    ]
